### PR TITLE
Updated README

### LINKED ISSUE #10: Document the permissions that the bot requires
Document (probably in the README), the permissions that the bot requires

### PR DESCRIPTION
**Pull request by antikitten**
Resolves #10 

Will mostly be creating a nicer UX with bot editing its messages, just thought I'd preempt it

### CODE REVIEW

**Comment by Danyc0** [comment]
Looks good

**Comment by Danyc0** [comment]
Damn it, I just realized, not in the *imperative mood*. Grrr

**Comment by antikitten** [comment]
Time to edit the head oop, I will save your log

**Comment by antikitten** [comment]
I have saved the log

**Comment by Danyc0** [comment]
Good job we can bet nobody else is working on the repo at the moment

**Pull request merged**
